name: Generated APK AAB (Upload - Create Artifact To Github Action)

on:

  push:
    branches:
      - 'release/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Set execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
          ./gradlew assemble
          ./gradlew bundleRelease

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ github.token }}
          publish_dir: ./doc

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: apk release
          path: ./app/build/outputs/apk/release

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: apk debug
          path: ./app/build/outputs/apk/debug

      - name: Upload Release Mapping
        uses: actions/upload-artifact@v4
        with:
          name: apk mapping
          path: ./app/build/outputs/mapping/release/mapping.txt
